In [7]:
import numpy as np
import pandas as pd
import sklearn as sk

In [2]:
# Exemplo de PCA

X = [
    [1, 1, 0, 1, 0, 0],
    [0, 1, 0, 0, 1, 1],
    [0, 0, 0, 1, 0, 1],
    [1, 0, 0, 0, 1, 0],
    [0, 0, 1, 0, 1, 0]
]

U, S, Vt = np.linalg.svd(X, full_matrices=False)

print(U.round(3))
print(np.diag(S.round(3)))
print(Vt.round(3))

print(np.allclose(X, U @ np.diag(S) @ Vt))


[[ 0.528  0.547  0.5    0.     0.414]
 [ 0.61  -0.195 -0.5   -0.577  0.084]
 [ 0.322  0.423 -0.5    0.577 -0.366]
 [ 0.404 -0.319  0.5   -0.    -0.696]
 [ 0.287 -0.618  0.     0.577  0.45 ]]
[[2.351 0.    0.    0.    0.   ]
 [0.    1.683 0.    0.    0.   ]
 [0.    0.    1.414 0.    0.   ]
 [0.    0.    0.    1.    0.   ]
 [0.    0.    0.    0.    0.799]]
[[ 0.396  0.484  0.122  0.362  0.553  0.396]
 [ 0.135  0.209 -0.367  0.576 -0.673  0.135]
 [ 0.707 -0.     0.    -0.     0.    -0.707]
 [-0.    -0.577  0.577  0.577  0.    -0.   ]
 [-0.353  0.624  0.563  0.061 -0.204 -0.353]]
True


In [3]:
# Exemplo de categórica -> numérica

df = pd.DataFrame({
    'cor': ['vermelho', 'amarelo', 'azul', 'vermelho', 'vermelho', 'amarelo'],
    'tamanho': ['p', 'p', 'm', 'm', 'g', 'gg']
})

X = pd.get_dummies(df)
print(X)

   cor_amarelo  cor_azul  cor_vermelho  tamanho_g  tamanho_gg  tamanho_m  \
0        False     False          True      False       False      False   
1         True     False         False      False       False      False   
2        False      True         False      False       False       True   
3        False     False          True      False       False       True   
4        False     False          True       True       False      False   
5         True     False         False      False        True      False   

   tamanho_p  
0       True  
1       True  
2      False  
3      False  
4      False  
5      False  


In [5]:
U, S, Vt = np.linalg.svd(X, full_matrices=False)

print(S)

[2.08187428 1.76056373 1.50804676 1.18552806 0.79133452 0.51021828]


In [11]:
from scipy.sparse.linalg import svds

U, S, Vt = svds(X.to_numpy(float), k=2)
print(S)

[1.76056373 2.08187428]
